services:

  redis:
    image: redis:alpine3.8
    env_file: .env

    ports:
     - "6379:6379"

    healthcheck:
      test: ["CMD", "redis-cli", "--raw", "incr", "ping"]
      interval: 5s
      timeout: 5s